// <auto-generated />
using System;
using Cloudativ.Assessment.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cloudativ.Assessment.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128091626_AddUserDomainAccess")]
    partial class AddUserDomainAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAuthProvider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalAuth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.AssessmentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiAnalysisJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessedDomainsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryScoresJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "StartedAt");

                    b.ToTable("AssessmentRuns");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResources")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Domain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("References")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remediation")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId");

                    b.HasIndex("Domain");

                    b.HasIndex("Severity");

                    b.HasIndex("AssessmentRunId", "Domain");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.GovernanceAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModelUsed")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComplianceGapsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ComplianceScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompliantAreasJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompliantControls")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NonCompliantControls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartiallyCompliantControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Standard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardDocumentVersion")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalControls")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId");

                    b.HasIndex("TenantId");

                    b.HasIndex("AssessmentRunId", "Standard")
                        .IsUnique();

                    b.HasIndex("TenantId", "Standard");

                    b.ToTable("GovernanceAnalyses");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.RawSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssessmentRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Domain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompressed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PayloadSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId");

                    b.HasIndex("AssessmentRunId", "Domain");

                    b.ToTable("RawSnapshots");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssessmentsUsedThisMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthlyAssessmentLimit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Plan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("YearlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId");

                    b.HasIndex("StripeSubscriptionId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AzureTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecretEncrypted")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("OnboardingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenAiApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OpenAiEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedComplianceStandards")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AzureTenantId");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.TenantSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoScheduleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomReportHeader")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledDomainsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeRawDataInReports")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManualDkimConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualDmarcConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManualSpfConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationEmails")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportLogoBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleCron")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAiScoring")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSettings");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.TenantUserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantRole")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("AppUserId", "TenantId")
                        .IsUnique();

                    b.ToTable("TenantUserAccess");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.UserDomainAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Domain")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "Domain")
                        .IsUnique();

                    b.ToTable("UserDomainAccess");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.AssessmentRun", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AssessmentRuns")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.Finding", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.AssessmentRun", "AssessmentRun")
                        .WithMany("Findings")
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentRun");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.GovernanceAnalysis", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.AssessmentRun", "AssessmentRun")
                        .WithMany()
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloudativ.Assessment.Domain.Entities.Tenant", "Tenant")
                        .WithMany("GovernanceAnalyses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.RawSnapshot", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.AssessmentRun", "AssessmentRun")
                        .WithMany("RawSnapshots")
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentRun");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("Cloudativ.Assessment.Domain.Entities.Subscription", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.TenantSettings", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Settings")
                        .HasForeignKey("Cloudativ.Assessment.Domain.Entities.TenantSettings", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.TenantUserAccess", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.AppUser", "AppUser")
                        .WithMany("TenantAccess")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cloudativ.Assessment.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.UserDomainAccess", b =>
                {
                    b.HasOne("Cloudativ.Assessment.Domain.Entities.AppUser", "AppUser")
                        .WithMany("DomainAccess")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("DomainAccess");

                    b.Navigation("TenantAccess");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.AssessmentRun", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("RawSnapshots");
                });

            modelBuilder.Entity("Cloudativ.Assessment.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AssessmentRuns");

                    b.Navigation("GovernanceAnalyses");

                    b.Navigation("Settings");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
